import pandas as pd

data_set = pd.read_csv('Iris.csv')
df = pd.DataFrame(data_set)
print(df)
print(df.head())
print(df.tail())
print(df.head(10))
print(df.tail(10))
print(df.info())
mean_SepalW = df['SepalWidthCm'].mean()
mean_SepalL = df['SepalLengthCm'].mean()
mean_PetalL = df['PetalLengthCm'].mean()
mean_PetalW = df['PetalWidthCm'].mean()
print(mean_SepalL)
print(mean_SepalW)
print(mean_PetalL)
print(mean_PetalW)
df['SepalWidthCm'].fillna(mean_SepalW, inplace=True)
print(df)
df['SepalLengthCm'].fillna(mean_SepalL, inplace=True)
print(df)
df['PetalLengthCm'].fillna(mean_PetalL, inplace=True)
print(df)
df['PetalWidthCm'].fillna(mean_PetalW, inplace=True)
print(df)
df['Species'].fillna('Iris-setosa', inplace=True)
print(df)
print(df.to_string())
