a=int(input())
b=int(input())
print("arithmetic operators")
print("addition a+b ",a+b)
print("subtraction a-b ",a-b)
print("multiplication a*b ",a*b)
print("division a/b ",a/b)
print("floor division a//b",a//b)
print("modulus a%b ",a%b)
print("exponentiation a**b ",a ** b)
print("relational operators")
print("greater than a>b ",a>b)
print("less than a<b ",a<b)
print("greater than or equal a>=b ",a>=b)
print("less than or equal to a<=b",a<=b)
print("equal to a==b ",a==b)
print("not equal to a!=b",a!=b)
print("logocal operators")
print("logical and operator a<b and a>b",a<b and a>b)
print("logical or operator a>=b or a<=b",a>=b or a<=b)
print("logical not operator not a==b",not a==b)
print("bitwise operator")
print("bitwise and a&b",a & b)
print("bitwise or a | b",a | b)
print("bitwise not ~a",~a)
print("bitwise xor a^b ",a ^ b)
print("bitwise right shift a>>",a>>1)
print("bitwise left shift a<<",a<<1)
x=input()
y=input()
print("membership operator")
print("membership in x in y", x in y)
print("membership not in x not in y",x not in y)
print("Identity operator")
print("identity operator i x is y", x is y)
print("identity operator is not x is not y", x is not y )